name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/checkout@v2
    - uses: c-hive/gha-npm-cache@v1
    - name: Install pkg global
      run: npm i -g pkg
    - name: Install JS dependencies
      run: npm i
    - name: Build the CLI
      run: npm run build:cli
    - name: Package the CLI
      run: pkg .
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
